---
- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present

- name: Download Kubernetes GPG key
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | \
    gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes repo
  copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /

- name: Install Kubernetes packages
  apt:
    update_cache: yes
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
