---
- name: Install PostgreSQL
  apt:
    name:
      - postgresql
      - postgresql-contrib
    state: present

- name: Install MariaDB
  apt:
    name:
      - mariadb-server
    state: present

- name: Install Redis
  apt:
    name: redis-server
    state: present
